### ISSUE TITLE
Estimated time to complete the project

### ISSUE THREAD

**Issue by mbuyukkarakas** [kosyfrances/rundeck-zabbix#12]
Hello Kosy,
When do you plan to complete the project. Its very interesting and we would like to use it.

Thank you. Best regards.
Mehmet

**Comment by kosyfrances** [comment]
Hello @mbuyukkarakas, 
Thanks for your interest in this project. I am trying to dedicate an hour or two on this, hoping to get it out of the way by end of December :)
