### ISSUE TITLE
Create reusable Zabbix api call utility

### ISSUE THREAD

**Issue by kosyfrances** [kosyfrances/rundeck-zabbix#15]
Subsequent tasks will require making Zabbix api calls. So far, we have an implementation [here](https://github.com/kosyfrances/rundeck_zabbix/blob/a5b9db47919c536ed2394c78af4eb7a6efdb4bff/zabbix_api_key.go) where we are making a call to Zabbix API to get the api key.  We can probably have a `utils` package when/if the project gets bigger. 

In this current issue, we want to accomplish the following:
- That zabbix_api_key.go file is converted to a utils.go file
- That we have a generic Zabbix api call function
- That the current functionality to get api key is derived from the generic Zabbix api call function

**Comment by tundeaoni** [comment]
@kosyfrances how about creating a api wrapper libraries for both zabbix and rundeck?

**Comment by kosyfrances** [comment]
Done. #16
