### ISSUE TITLE
Rename project or keep existing name

### ISSUE THREAD

**Issue by kosyfrances** [kosyfrances/rundeck-zabbix#37]
The project's name is currently `rundeck-zabbix`. I was wondering if it can be renamed to something cool 😎 , but I do not have a better cool name. I was thinking of the following:

- [x] Leave it as rundeck-zabbix

- [ ] Call it zabideck maybe?

- [ ] Anyone got ideas?

**Comment by impactmass** [comment]
Name suggestion: **coco** 😊

**Comment by sundayguru** [comment]
I think leaving it as `rundeck-zabbix` will help users locate the package

**Comment by kosyfrances** [comment]
Sticking with the original name.
