### ISSUE TITLE
project build

### ISSUE THREAD

**Issue by VenanceElegba** [kosyfrances/rundeck-zabbix#52]
Hi thanks for this interesting project.

Can you help me about project build.

I'm trying to build project using the following step on ubuntu 16.04 but he didn't work.

#For build specific to your machine's OS
make build
#For Linux OS
make build-linux

Then i'm try to run Go project using the Go main file but i didn't find it on project.

**Comment by kosyfrances** [comment]
Hi, thanks for reporting the bug. I fixed the issue and you can try with the [new release](https://github.com/kosyfrances/rundeck-zabbix/releases/tag/rundeck-zabbix-v0.1.1). Let me know if that solves the issue.

Here is the [main.go](https://github.com/kosyfrances/rundeck-zabbix/blob/master/cli/main.go) file as well.

**Comment by VenanceElegba** [comment]
Hi thanks for your return.
I will try again with  main.go file provide and make you feedback.
Thanks

**Comment by kosyfrances** [comment]
Could you please also try using the make command as well? Just to be sure my fix resolved your issue?

**Comment by VenanceElegba** [comment]
I'm try to use make command again with main.go in project root but i get the same issue.

**Comment by kosyfrances** [comment]
On a fresh ubuntu virtual machine, I downloaded the latest release, untarred it, did a cd into the rundeck-zabbixv0.1.1 directory, ran `make build` and the binary was created. What error do you get when you try to create the binary? That will help me understand what problem you are having.

**Comment by VenanceElegba** [comment]
Ok let me try it and come back to you.

**Comment by VenanceElegba** [comment]
I try again on a fresh ubuntu virtual machine and binary generation is ok now.

So in my case i have zabbix server and rundeck install in the same machine.

To run middleware i need to specify path to .config.json file.

rundeck-zabbix run job --project=RUNDECK-PROJECT --trigger={TRIGGER.NAME} --event={EVENT.ID} --config="/path/to/.config.json"

That file is relative to zabbix or rundeck.

**Comment by kosyfrances** [comment]
The file is relative to what calls it. in the case of running a job, it is relative to Zabbix.

**Comment by VenanceElegba** [comment]
ok thanks
